@startuml
class Affiliate{
    - String firstName
    - String SecondName
    - Date birthDate
    - int id
    - int INITIAL_NUMBER = 1000
    - int LAST_NUMBER
    + Affiliate(String firstName, String SecondName, Date birthDate)
    - int getAndIncrement()
}
@enduml